#!/usr/bin/env python3
"""Turns conquest/unity/Screenshots/polish/numbers.jsonl (written by PolishCaptureTests) into a Markdown table per
decision. Usage: polish_table.py numbers.jsonl > NUMBERS.md"""
import json
import sys

COLUMNS = {
    "a-banner-size": [("zoom", "zoom"), ("stacked_clear", "stacked clear"), ("stack_width_tiles", "widest stack (tiles)"), ("cloth_px_S", "S cloth px"), ("cloth_px_M", "M cloth px"), ("cloth_px_L", "L cloth px"),
                      ("total_px_M", "M cloth+beam px"), ("cloth_px_1x_M", "M cloth @1x"), ("beam_px_1x_M", "M beam @1x"),
                      ("target_M_px", "M target px"), ("target_M_css", "M target css"), ("target_M_1x_px", "M target @1x px"),
                      ("target_M_1x_phone_css", "M target @1x on phone css"), ("targets_meeting_min", "targets >= min"), ("min_css", "min css"), ("touch_hit_px", "touch hit px (44 css)"), ("touch_hit_overlaps", "touch hit overlaps"), ("zoom_for_44css_M", "zoom for 44 css"), ("overlap_banner_structure", "banner/structure overlaps"),
                      ("overlap_banner_banner", "banner/banner overlaps")],
    "b-stack": [("zoom", "zoom"), ("banners_visible", "banners visible"), ("stacked_clear", "stacked banners with >= 60% cloth clear"),
                ("stack_width_tiles", "widest stack (tiles)"), ("badges", "badges"), ("overlap_banner_banner", "banner/banner overlaps"),
                ("overlap_banner_structure", "banner/structure overlaps"), ("target_M_px", "M target px"), ("targets_meeting_min", "targets >= min")],
    "c-selection": [("zoom", "zoom"), ("selection_changed_pct", "pixels changed by selecting %"), ("rings", "tile rings"),
                    ("card_title_px", "card title px"), ("card_body_px", "card body px"), ("card_body_css", "card body css")],
    "d-camera": [("zoom", "zoom"), ("crisp", "crisp 2:1"), ("coverage_pct", "viewport showing map %"), ("top_row_clear_of_bar", "top row below HUD bar"),
                 ("cloth_px_M", "M cloth px"), ("target_M_css", "M target css"), ("targets_meeting_min", "targets >= min"), ("zoom_for_44css_M", "zoom for 44 css"),
                 ("touch_hit_overlaps", "touch hit overlaps")],
    "e-layering": [("dots", "path dots"), ("dots_under_art", "dots under tile or structure art"), ("dots_over_banners", "dots over banners"),
                   ("overlap_banner_structure", "banner/structure overlaps")],
    "f-footprint": [("footprint_off_map_tiles", "off-map tiles"), ("footprint_covers_other_rule_tiles", "covers other structures' tiles"),
                    ("overlap_banner_structure", "banner/structure overlaps")],
    "g-placeholder": [("water", "water"), ("water_border_contrast", "border contrast"), ("block_wall_px", "block wall px @1x")],
}


def main(path):
    rows = [json.loads(line) for line in open(path, encoding="utf-8") if line.strip()]
    out = ["# Map polish: measured numbers", "",
           "Generated by conquest/tools/unity/polish_capture.sh from numbers.jsonl. Phone figures assume 2.625 device px per CSS px (412 dp wide); desktop is 1:1. Minimum target: 44 CSS px on touch, 24 on a mouse. Overlaps: pairs sharing more than 25 percent of the smaller rectangle (banner cloth vs structure picture bounds).", ""]
    for decision, columns in COLUMNS.items():
        mine = [r for r in rows if r.get("decision") == decision]
        if not mine:
            continue
        out.append("## " + decision)
        out.append("")
        out.append("| cand | size | " + " | ".join(title for _, title in columns) + " |")
        out.append("|---|---|" + "---|" * len(columns))
        for r in mine:
            out.append("| " + r["choice"] + " | " + r["size"] + " | " + " | ".join(str(r.get(key, "-")) for key, _ in columns) + " |")
        out.append("")
    print("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1])
