#!/usr/bin/env python3
"""Writes dotnet/Conquest.Tests/golden/shore-autotile.golden.json from the pilot's missing/mwater.py.

The C# twin is Conquest.Presentation/Iso/ShoreAutotile.cs; its test compares all 256 raw 8-neighbour masks and the 47
canonical codes with this file, so the C# can never drift from the Python that named the water pictures.

    Blender python (needs numpy): .../python3.13 conquest/tools/assets/shore_golden.py <bd1971-pilot dir> [out-file]

mwater.py imports Blender-side helpers (detail_geo, detail_mats, detail_pal) that this script does not need, so they are
replaced by empty stand-ins before the import. Only code_of, name_of, all_codes and the bit tables are used.
"""
import json
import os
import sys
import types


def load_mwater(pilot_dir):
    class _Stub(types.ModuleType):
        def __getattr__(self, name):
            return lambda *a, **k: {}

    for name in ("detail_geo", "detail_mats", "detail_pal"):
        mod = _Stub(name)
        if name == "detail_pal":
            mod.PAL = {}
        sys.modules[name] = mod
    sys.path.insert(0, os.path.join(pilot_dir, "missing"))
    import mwater  # noqa: E402
    return mwater


# raw-mask bit order = mwater.all_codes: ne, se, sw, nw, n, e, s, w
RAW_ORDER = [(0, 1), (1, 0), (0, -1), (-1, 0), (-1, 1), (1, 1), (1, -1), (-1, -1)]


def build(mw):
    raw_names = []
    raw_codes = []
    for m in range(256):
        land = [d for i, d in enumerate(RAW_ORDER) if m & (1 << i)]
        code = mw.code_of(land)
        raw_codes.append(code)
        raw_names.append(mw.name_of(code))
    codes = {str(c): mw.name_of(c) for c in mw.all_codes()}
    assert len(codes) == 47, len(codes)
    return {
        "_note": "Generated by conquest/tools/assets/shore_golden.py from the pilot's missing/mwater.py. raw_codes[m] and "
                 "raw_names[m] are code_of/name_of for the raw 8-neighbour land mask m (bit order ne, se, sw, nw, n, e, s, w; "
                 "art-frame offsets (0,1),(1,0),(0,-1),(-1,0),(-1,1),(1,1),(1,-1),(-1,-1)).",
        "raw_codes": raw_codes,
        "raw_names": raw_names,
        "codes": codes,
    }


def main():
    pilot = sys.argv[1]
    out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "..", "dotnet", "Conquest.Tests", "golden",
        "shore-autotile.golden.json")
    data = build(load_mwater(pilot))
    with open(out, "w") as f:
        json.dump(data, f, indent=1, sort_keys=True)
        f.write("\n")
    print("wrote", os.path.normpath(out), "47 codes, 256 raw masks")


if __name__ == "__main__":
    main()
