<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>Conquest.Presentation</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Conquest.Core\Conquest.Core.csproj" />
  </ItemGroup>

</Project>
