using Conquest.Content.Model;

namespace Conquest.Content.Validation
{
    internal static class ArrivalRules
    {
        public static void Check(ScenarioData s, ErrorSink errors)
        {
            for (int i = 0; i < s.Arrivals.Count; i++)
            {
                ArrivalData a = s.Arrivals[i];
                string path = "$.arrivals[" + i + "]";
                if (a.Turn >= s.Settings.MaxTurns)
                {
                    errors.Add(path + ".turn", "arrival.turn", "turn " + a.Turn + " is not before max_turns " + s.Settings.MaxTurns);
                }

                PlayerData? player = EntryRules.FindPlayer(s, a.Slot);
                if (player == null)
                {
                    errors.Add(path + ".slot", "arrival.slot", "slot '" + a.Slot + "' is not a player");
                    continue;
                }

                CheckEntry(s, a, player, path, errors);
                CheckUnits(a, path, errors);
            }
        }

        private static void CheckEntry(ScenarioData s, ArrivalData a, PlayerData player, string path, ErrorSink errors)
        {
            if (a.EntryGroup == null)
            {
                if (player.StartMode == "entry_tiles")
                {
                    errors.Add(path + ".entry", "arrival.entry_required", "slot '" + a.Slot + "' arrives through an entry group");
                }

                return;
            }

            EntryGroupData? group = null;
            foreach (EntryGroupData g in s.EntryGroups)
            {
                if (g.Id == a.EntryGroup)
                {
                    group = g;
                }
            }

            if (group == null)
            {
                errors.Add(path + ".entry.group", "arrival.entry", "entry group '" + a.EntryGroup + "' does not exist");
                return;
            }

            if (group.Slot != a.Slot)
            {
                errors.Add(path + ".entry.group", "arrival.entry", "entry group '" + group.Id + "' belongs to " + group.Slot + ", not " + a.Slot);
                return;
            }

            bool wantsWater = false;
            foreach (UnitGroup u in a.Units)
            {
                wantsWater |= u.Role == Vocabulary.Transport;
            }

            foreach (TilePoint t in group.Tiles)
            {
                string? terrain = s.Map.TerrainAt(t.X, t.Y);
                bool water = terrain != null && Vocabulary.IsWater(terrain);
                if (wantsWater && !water)
                {
                    errors.Add(path + ".entry.group", "arrival.transport_terrain", "boats need an entry group made only of water tiles");
                    return;
                }
            }
        }

        private static void CheckUnits(ArrivalData a, string path, ErrorSink errors)
        {
            if (a.Units.Count == 0)
            {
                errors.Add(path + ".units", "arrival.empty", "an arrival needs at least one unit");
            }

            bool hasCommander = false;
            for (int i = 0; i < a.Units.Count; i++)
            {
                UnitGroup u = a.Units[i];
                string p = path + ".units[" + i + "].role";
                if (!Vocabulary.Contains(Vocabulary.Units, u.Role))
                {
                    errors.Add(p, "arrival.role", "unknown unit role '" + u.Role + "'");
                    continue;
                }

                if (u.Role == Vocabulary.Militia)
                {
                    errors.Add(p, "arrival.role_not_allowed", "base guards are generated by bases, never delivered");
                }

                hasCommander |= u.Role == Vocabulary.Commander;
            }

            if (a.AttachToFirstCommander && !hasCommander)
            {
                errors.Add(path + ".attach_to_first_commander", "arrival.attach_no_commander", "attach is set but the arrival has no commander");
            }
        }
    }
}
